name: push-image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and release to DockerHub
        env:
          NAME: dmstjq12 # 계정 명
          REPO: docker-node-nas # 레포 이름
          VERSION: 20.9-alpine
        run: |
          docker build -t $REPO --build-arg VERSION=$VERSION .
          docker tag $REPO:latest $NAME/$REPO:$VERSION
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:$VERSION
          docker push $NAME/$REPO:latest
